
from openai import OpenAI
import requests
from PIL import Image
import os
import time

# ============= CONFIGURATION - EDIT HERE =============
API_KEY = r"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"
IMAGE_PATH = r"tryIn\000003.jpg"
# Use the mask generated by the lip-masking function (Lips=Black, Rest=White)
MASK_PATH = r"tryOut\000003_lips_mask.jpg"
NEW_LIP_COLOR = "matte pink lipstick" 
OUTPUT_PATH = r"tryOut\000003_edited_lips.png"
# =====================================================

def prepare_mask(mask_path):
    """
    Converts Black/White mask to Transparent/Opaque RGBA for OpenAI API.
    Black (Lips) -> Transparent (Alpha 0) -> Area to be edited
    White (Skin) -> Opaque (Alpha 255) -> Area to keep original
    """
    print(f"Preparing edit mask from: {mask_path}")
    with Image.open(mask_path).convert("L") as mask:
        w, h = mask.size
        # Create a white background RGBA image
        new_mask = Image.new("RGBA", (w, h), (255, 255, 255, 255))
        
        for y in range(h):
            for x in range(w):
                value = mask.getpixel((x, y))
                if value < 100:  # The black area detected as lips
                    new_mask.putpixel((x, y), (255, 255, 255, 0)) # Transparent
                else:
                    new_mask.putpixel((x, y), (255, 255, 255, 255)) # Opaque
        
        new_path = os.path.splitext(mask_path)[0] + "_lip_editmask.png"
        new_mask.save(new_path, "PNG")
    return new_path

def convert_image_to_rgba(image_path):
    with Image.open(image_path) as img:
        img = img.convert("RGBA")
        new_path = os.path.splitext(image_path)[0] + "_rgba_temp.png"
        img.save(new_path, "PNG")
    return new_path
"""
def change_lip_color(image_path, mask_path, new_color, output_path):
    client = OpenAI(api_key=API_KEY)
    image_temp = None
    mask_temp = None

    try:
        image_temp = convert_image_to_rgba(image_path)
        mask_temp = prepare_mask(mask_path)

        print(f"\nSending Lip Edit request: {new_color}...")

        with open(image_temp, "rb") as img_file, open(mask_temp, "rb") as mask_file:
            # The prompt is key: We emphasize keeping the texture of the lips
            response = client.images.edit(
                model="gpt-image-1",
                image=img_file,
                mask=mask_file,
                prompt=f"Photorealistic edit. Change ONLY the lip color to {new_color}. Keep face, skin, lighting and photo identical.",
                size="1024x1024"
            )

        image_url = response.data[0].url
        img_data = requests.get(image_url, timeout=30).content
        with open(output_path, "wb") as f:
            f.write(img_data)

        print(f"✅ Success! Saved to: {output_path}")
        return output_path

    except Exception as e:
        print(f"❌ Error: {e}")
        return None
    finally:
        # Cleanup temp files
        for f in [image_temp, mask_temp]:
            if f and os.path.exists(f):
                try: os.remove(f)
                except: pass
"""
"""
def change_lip_color(image_path, mask_path, new_color, output_path):
    client = OpenAI(api_key=API_KEY)
    image_temp = None
    mask_temp = None

    try:
        image_temp = convert_image_to_rgba(image_path)
        mask_temp = prepare_mask(mask_path)

        print(f"\nSending Lip Edit request: {new_color}...")

        with open(image_temp, "rb") as img_file, open(mask_temp, "rb") as mask_file:
            response = client.images.edit(
                model="gpt-image-1.5",          # or try "gpt-image-1.5" / "gpt-image-2" if you have access
                image=img_file,
                mask=mask_file,
                prompt=f"Photorealistic edit. Change ONLY the lip color to {new_color}. Keep face, skin, lighting, texture and natural shadows unchanged. Make it realistic and blended naturally.",
                size="1024x1024",
                response_format="b64_json"    # ← Explicitly request base64
            )

        # Handle base64 response
        b64_data = response.data[0].b64_json
        import base64
        img_data = base64.b64decode(b64_data)

        with open(output_path, "wb") as f:
            f.write(img_data)

        print(f"✅ Success! Saved to: {output_path}")
        return output_path

    except Exception as e:
        print(f"❌ Error: {e}")
        import traceback
        traceback.print_exc()   # ← Add this for better debugging
        return None
    finally:
        for f in [image_temp, mask_temp]:
            if f and os.path.exists(f):
                try: 
                    os.remove(f)
                except: 
                    pass
"""

import base64
import os
from PIL import Image
import requests
from openai import OpenAI

def change_lip_color(image_path, mask_path, new_color, output_path):
    client = OpenAI(api_key=API_KEY)
    image_temp = None
    mask_temp = None

    try:
        image_temp = convert_image_to_rgba(image_path)
        mask_temp = prepare_mask(mask_path)

        print(f"\nSending Lip Edit request: {new_color}...")

        with open(image_temp, "rb") as img_file, open(mask_temp, "rb") as mask_file:
            response = client.images.edit(
                model="gpt-image-2",   # or "gpt-image-1.5" if available
                image=img_file,
                mask=mask_file,

                prompt = (
    "Change ONLY the color of the lips inside the masked area to matte soft pink lipstick. "
    "Do NOT change anything else in the image. "
    "Keep the skin, teeth, eyes, hair, lighting, shadows, texture, background and all other details 100% identical to the original photo. "
    "Photorealistic, natural blend only on the lips, no other modifications."
),
                size="1024x1024",
                # DO NOT pass response_format for gpt-image-1
            )


        # GPT Image models return b64_json by default
        b64_data = response.data[0].b64_json
        img_data = base64.b64decode(b64_data)

        with open(output_path, "wb") as f:
            f.write(img_data)

        print(f"✅ Success! Saved to: {output_path}")
        return output_path

    except Exception as e:
        print(f"❌ Error: {e}")
        import traceback
        traceback.print_exc()
        return None
    finally:
        # Cleanup temp files
        for f in [image_temp, mask_temp]:
            if f and os.path.exists(f):
                try:
                    os.remove(f)
                except:
                    pass


"""              
  prompt=(
                    f"Photorealistic edit. Change ONLY the lip color to {new_color}. "
                    "Keep the exact same skin tone, lighting, texture, natural shadows, "
                    "and all other details of the photo unchanged. Highly detailed, no artifacts."
                ),"""
               
               
if __name__ == "__main__":
    change_lip_color(IMAGE_PATH, MASK_PATH, NEW_LIP_COLOR, OUTPUT_PATH)