import base64

from openai import OpenAI
import requests
from PIL import Image
import os
import time

# ============= CONFIGURATION - EDIT HERE =============
API_KEY = r"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"
IMAGE_PATH = r"tryIn\000003.jpg"
# Use the mask generated by the eye circles masking function (Eyes=Black, Rest=White)
MASK_PATH = r"tryOut\000003_eye_circles_mask.jpg"
NEW_EYE_COLOR = "bright green eyes" 
OUTPUT_PATH = r"tryOut\000003_edited_eyes.png"
# =====================================================

def prepare_mask(mask_path):
    """
    Converts Black/White mask to Transparent/Opaque RGBA for OpenAI API.
    Black (Eyes) -> Transparent (Alpha 0) -> Area to be edited
    White (Rest) -> Opaque (Alpha 255) -> Area to keep original
    """
    print(f"Preparing edit mask from: {mask_path}")
    with Image.open(mask_path).convert("L") as mask:
        w, h = mask.size
        new_mask = Image.new("RGBA", (w, h), (255, 255, 255, 255))
        
        for y in range(h):
            for x in range(w):
                value = mask.getpixel((x, y))
                if value < 100:  # The black area detected as eyes
                    new_mask.putpixel((x, y), (255, 255, 255, 0)) # Transparent (edit area)
                else:
                    new_mask.putpixel((x, y), (255, 255, 255, 255)) # Opaque (keep original)
        
        new_path = os.path.splitext(mask_path)[0] + "_eye_editmask.png"
        new_mask.save(new_path, "PNG")
    return new_path

def convert_image_to_rgba(image_path):
    with Image.open(image_path) as img:
        img = img.convert("RGBA")
        new_path = os.path.splitext(image_path)[0] + "_rgba_temp.png"
        img.save(new_path, "PNG")
    return new_path

def change_eye_color(image_path, mask_path, new_color, output_path):
    client = OpenAI(api_key=API_KEY)
    image_temp = None
    mask_temp = None

    try:
        image_temp = convert_image_to_rgba(image_path)
        mask_temp = prepare_mask(mask_path)

        print(f"\nSending Eye Color Edit request: {new_color}...")


        with open(image_temp, "rb") as img_file, open(mask_temp, "rb") as mask_file:
            response = client.images.edit(
                model="gpt-image-2",   # or "gpt-image-1.5" if available
                image=img_file,
                mask=mask_file,
                prompt= (new_color),
                size="1024x1024",
            )


        # GPT Image models return b64_json by default
        b64_data = response.data[0].b64_json
        img_data = base64.b64decode(b64_data)


        with open(output_path, "wb") as f:
            f.write(img_data)

        print(f"✅ Success! Saved to: {output_path}")
        return output_path

    except Exception as e:
        print(f"❌ Error: {e}")
        return None
    finally:
        # Cleanup temp files
        for f in [image_temp, mask_temp]:
            if f and os.path.exists(f):
                try: os.remove(f)
                except: pass

if __name__ == "__main__":
    change_eye_color(IMAGE_PATH, MASK_PATH, NEW_EYE_COLOR, OUTPUT_PATH)
